#!/bin/bash

# Check if cost collection is working by examining what should be in backend logs

echo "======================================"
echo "Cost Collection Logs Checker"
echo "======================================"
echo ""
echo "✓ Fixes Applied:"
echo "  1. Database: AzureCostRecord now upserts subscription before creating record"
echo "  2. Backend: Users array correctly extracted from {users: [...]} response"
echo ""
echo "📋 What to check in your BACKEND terminal logs:"
echo ""
echo "1. User collection:"
echo "   ✓ 'Collecting cost snapshots for 4 users'"
echo ""
echo "2. Azure API calls (for each user + subscription):"
echo "   ✓ 'Generating cost details report for subscription...'"
echo "   ✓ 'Cost report generation started. Operation ID: ...'"
echo "   ✓ 'Poll attempt N: Status = InProgress|Queued|Completed'"
echo "   ✓ 'Cost report ready. Download URL obtained.'"
echo "   ✓ 'Downloading cost details CSV from...'"
echo "   ✓ 'Parsed X cost records from CSV'"
echo ""
echo "3. Data processing:"
echo "   ✓ 'Processing X cost detail records'"
echo "   ✓ 'Saved service cost for SERVICE_NAME (SERVICE_TYPE): \$X.XX'"
echo "   ✓ 'Saved resource breakdown for RESOURCE_NAME: METER_NAME = \$X.XX'"
echo ""
echo "4. Completion:"
echo "   ✓ 'Saved cost snapshot for user USERNAME, subscription SUBSCRIPTION_NAME: \$X.XX'"
echo "   ✓ 'Daily cost snapshot collection completed'"
echo ""
echo "❌ Common Errors to Look For:"
echo ""
echo "1. 'Failed to fetch cost data for subscription...'"
echo "   → Azure API error or permissions issue"
echo ""
echo "2. 'Cost report generation failed: ...'"
echo "   → Azure rejected the request (check permissions, quota)"
echo ""
echo "3. 'Cost report generation timed out after 60 attempts'"
echo "   → Azure API taking too long (> 5 minutes)"
echo ""
echo "4. 'No cost data available for subscription...'"
echo "   → Subscription has no costs for yesterday's date"
echo ""
echo "5. 'Failed to save service cost: ...'"
echo "   → Database error when storing ServiceCostRecord"
echo ""
echo "6. 'Failed to save resource breakdown: ...'"
echo "   → Database error when storing ResourceCostBreakdown"
echo ""
echo "======================================"
echo ""
echo "💡 If you don't see any logs:"
echo "   - Collection might still be running (Azure API is slow)"
echo "   - Check if backend process is running: lsof -ti:3003"
echo "   - Trigger manually: curl -X POST http://localhost:3003/azure/sync/cost-snapshots"
echo ""
echo "💡 If 'No cost data available':"
echo "   - Azure might not have data for yesterday yet"
echo "   - Try the OLD sync which uses last 30 days:"
echo "     curl -X POST http://localhost:3003/azure/sync/costs"
echo ""
