blank_issues_enabled: true
contact_links:
  - name: 💬 Community Discussions
    url: https://github.com/darshan45672/Ai-for-FinOps/discussions
    about: Join the community for general discussions, ideas, and Q&A
  - name: 📚 Documentation
    url: https://github.com/darshan45672/Ai-for-FinOps#readme
    about: Check out our documentation for setup and usage guides
  - name: 🔒 Security Issue
    url: https://github.com/darshan45672/Ai-for-FinOps/security/advisories/new
    about: Report a security vulnerability privately
